# ---------- Stage 1:  ----------
FROM node:16-slim AS builder

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the app
RUN npm run build


# ---------- Stage 2: Run the built app using a lightweight server ----------
FROM nginx:alpine AS production

# Copy build output from builder stage to nginx html folder
COPY --from=builder /app/build /usr/share/nginx/html

# Expose port 3000 (or 80 if using Nginx default)
EXPOSE 80


# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
